### ISSUE TITLE
error: listen EADDRINUSE: address already in use 127.0.0.1:29815

### ISSUE THREAD

**Issue by sergerdn** [CheshireCaat/browser-with-fingerprints#1]
It occurs when:
- I have one or more running BAS instances on the same machine.
- I execute multiple scripts on the same machine at the same time.
- I execute multiple tests on the same machine at the same time.

I believe that the port is hardcoded in this line of code: https://github.com/CheshireCaat/browser-with-fingerprints/blob/4e263c96c8fa192acb13b4d250091d91acee4ad8/src/plugin/connector/server/index.js#L33

Is there any way to select a random port for each start to avoid these errors?

Note that I have used https://github.com/CheshireCaat/selenium-with-fingerprints.

**Comment by CheshireCaat** [comment]
Please try to use latest version - `1.1.4` for `selenium-with-fingerprints`.
