### ISSUE TITLE
read ECONNRESET

### ISSUE THREAD

**Issue by brodev3** [CheshireCaat/browser-with-fingerprints#13]
![image](https://github.com/CheshireCaat/browser-with-fingerprints/assets/121391659/4680edcb-7b82-47d0-8a6a-f43dc816269f)
An error occurs when working with a proxy, previously everything worked fine, literally, 2 days ago problems with the connection started, I tried the proxy on a naked playwright, everything works fine

**Comment by bablosoft** [comment]
Please attach minimal source code.

**Comment by bro-web3-dev** [comment]
plugin.useProfile(`profilesStorage/${worker.name}`, {
      loadProxy: false, //  if set to true the error also occurs
    });
    if (profile.fingerprint){
      plugin.useFingerprint(JSON.stringify(profile.fingerprint));
    };

    if (profile.proxy){
      plugin.useProxy(`https://${profile.proxy.login}:${profile.proxy.pass}:${profile.proxy.ip}:${profile.proxy.port}`, {
        changeTimezone: true,
        changeGeolocation: true,  
      });
    };

    let browser = await plugin.launchPersistentContext(`profilesStorage/${worker.name}`, {
      headless: false,
      // args: [`--proxy-server=${profile.proxy.ip}:${profile.proxy.port}`],
      // proxy:{
      //   server: `http://${profile.proxy.ip}:${profile.proxy.port}`,
      //   username: `${profile.proxy.login}`,
      //   password: `${profile.proxy.pass}`
      // }
    });
   this code does not work correctly, I open 50 profiles, an error occurs when opening, I changed the proxy, the same thing

**Comment by bro-web3-dev** [comment]
you answer very quickly! thank you for your attention

**Comment by CheshireCaat** [comment]
It seems to me that the problem may be with your proxy server or proxy provider - I tested your code with a fresh IPv4 proxy and was unable to reproduce the issue.

It means there is clearly no error on the plugins side - try testing with a different proxy or on a different machine if possible.

**Comment by bro-web3-dev** [comment]
> It seems to me that the problem may be with your proxy server or proxy provider - I tested your code with a fresh IPv4 proxy and was unable to reproduce the issue.
> 
> It means there is clearly no error on the plugins side - try testing with a different proxy or on a different machine if possible.

the error occurs spontaneously, sometimes it works, but sometimes it crashes, is there any way to determine what the problem is more specifically? I used proxies from 3 different providers and the same thing, but at the same time everything worked for me for the whole day 3 days ago, the last 2 days I have been having these errors, I used a proxy in playwright, without your plugin, I was able to open 50 profiles, with the plugin I can’t I can do this, an error occurs on some profile and the program crashes

**Comment by bro-web3-dev** [comment]
> It seems to me that the problem may be with your proxy server or proxy provider - I tested your code with a fresh IPv4 proxy and was unable to reproduce the issue.
> 
> It means there is clearly no error on the plugins side - try testing with a different proxy or on a different machine if possible.

I changed the machine, changed the proxy provider, changed the provider, same problem

**Comment by CheshireCaat** [comment]
Based on the error you indicated, I simply cannot understand the place where it occurs. At the moment, I can advise you to handle errors additionally in this way:

```js
process.on('uncaughtException', (err) => {
  console.error(err);
});
```

This is not a very good option, but in theory it can help avoid the application crashing. Please try to find out where the error occurs within the plugin, as I cannot reproduce it myself. If you can find it, let me know, I’ll also do some checks a little later.

**Comment by bro-web3-dev** [comment]
![image](https://github.com/CheshireCaat/browser-with-fingerprints/assets/121391659/52883328-f20d-46bd-8f05-2ce5934bd684)

v19.3.0
Thank you again for your prompt response, your advice helped to avoid the program crashing
