### ISSUE TITLE
docs: Technical details about plugin's behavior during first and subsequent launches

### ISSUE THREAD

**Issue by sergerdn** [CheshireCaat/browser-with-fingerprints#2]
Can you please update the documentation for `browser-with-fingerprints` to include more information on how the plugin works during the first launch and subsequent launches?

It would be great if you could add a new section called "Technical Details" after the Architecture section that explains the following:
- During the first launch of browser-with-fingerprints, the plugin will download the necessary dependencies to the `FINGERPRINT_CWD` folder via the independent `bas-remote-node` project.
- The dependencies that are downloaded during the first launch include browser, scripts, and some other files that are needed for the plugin to function properly.
- The specific dependencies that are downloaded may vary depending on the version of `browser-with-fingerprints` that is being used, as well as the specific browser being used to run your script.
- Subsequent launches of the plugin will not download any additional dependencies unless the remote script `FingerprintPlugin` has been updated. In this case, the plugin will download and update its dependencies as needed.
- It is important to note that the `FINGERPRINT_CWD` folder should not be deleted between script runs, as this could result in the need to redownload dependencies and slow down execution time.
- Each of your scripts should run with a different `FINGERPRINT_CWD` folder because each copy of your script can update dependencies at the same time and it may break the functionality of your script.

Of course, I provided just an example because I do not completely understand how it works. It would be great if you could provide more detailed information on this topic.

**Comment by bablosoft** [comment]
No, I don't authorize these changes.

**Comment by bablosoft** [comment]
I'm not ready to spend time of the team to documenting library internals. There are much more important things to do.

**Comment by bablosoft** [comment]
> Should it be reopened and marked as "wait for something"?

No, I don't think that these changes are necessary, so I closed this ticket.
