### ISSUE TITLE
CanvasRenderingContext2D.getImageData: suspicious pixel data

### ISSUE THREAD

**Issue by TheGP** [CheshireCaat/browser-with-fingerprints#20]
Creep JS detects some `trash` from the fingerprint: `CanvasRenderingContext2D.getImageData: suspicious pixel data`
I see in the fingerprint some data in canvas, but not sure what it means:

```"canvas":"6f7184a9f7b9e522f1bb67d200be83b58313e9c61b8dabdb4f9c258599d1586926ba948a2c037522aa375fabf2374ac0cfe8f4997d4f0ca09c31839b634b160b7b8183837b7f7c7c7c7d8283828280817c7b7c7c827b80817f7c7c817d7b837b7e7e7b7c7f7d808080837b7f817d817c818282"```

**Comment by bablosoft** [comment]
Already been discussed, use PerfectCanvas

https://github.com/CheshireCaat/puppeteer-with-fingerprints/issues/31

**Comment by TheGP** [comment]
Thank you, its because it is adding noise by default.

**Comment by bablosoft** [comment]
Disabling adding noise will help, but will expose part of your real fingerprint.

I doubt that this is your intention.

You need to use PerfectCanvas.

**Comment by TheGP** [comment]
To use paid ones I need to save all canvases with CanvasInspector and then put it inside `perfectCanvasRequest` param along with a key, correct?

**Comment by TheGP** [comment]
> Disabling adding noise will help, but will expose part of your real fingerprint.

But how to do it?
