### ISSUE TITLE
Custom function to get IP data

### ISSUE THREAD

**Issue by TheGP** [CheshireCaat/browser-with-fingerprints#22]
Is it possible to use "custom function" to get IP information like in BAS itself?

I tried to pass string with JS function but it looks like it didn't work ( "Custom IP information function parameter is not a function" )

I see that you can create it in BAS, but how to do it without? Actually settings just custom domain to get IP info would be nice.

**Comment by CheshireCaat** [comment]
Right now you can use only the `database` (default) or the `ip-api` method, as described [here](https://github.com/CheshireCaat/browser-with-fingerprints/blob/master/src/index.d.ts#L174). Custom functions are not supported yet.
