### ISSUE TITLE
ERR: crypto is not defined

### ISSUE THREAD

**Issue by dr3adx** [CheshireCaat/browser-with-fingerprints#31]
ReferenceError: crypto is not defined
    at RemoteEngine.runFunction (C:\Users\x\node_modules\browser-with-fingerprints\src\plugin\connector\engine.js:58:65)
    at async C:\x\node_modules\browser-with-fingerprints\src\plugin\connector\index.js:44:36 ReferenceError: crypto is not defined
    at RemoteEngine.runFunction (C:\x\node_modules\browser-with-fingerprints\src\plugin\connector\engine.js:58:65)
    at async C:\x\node_modules\browser-with-fingerprints\src\plugin\

_you forgot to import crypto_

**this plugin chromium 129 is also flagged on pixelscan.net since version 128**

**Comment by CheshireCaat** [comment]
thanks for the bug, fixed it - strange, but it didn't give me any errors during tests.

> this plugin chromium 129 is also flagged on pixelscan.net since version 128

I saw your ticket in `playwright-with-fingerprints`, I couldn't repeat it - my fingerprint is all green, I need a code example to repeat the problem, please attach it there (you can also send the fingerprint where the problem occurs to the email - likangt2012@gmail.com).
