### ISSUE TITLE
How to use Fingerswitcher in js without browser api such as pupeteer, playwright... ?

### ISSUE THREAD

**Issue by mmolab** [CheshireCaat/browser-with-fingerprints#33]
Hello,

I just only need get fingerprint and use in our side, no need  pupeteer, playwright... or any browser api.

How to get fingerprint in js with api key from FingerSwicher? Thanks!

**Comment by CheshireCaat** [comment]
You can get fingerprints without using browsers, but it doesn't make much sense - you won't be able to apply them correctly without the engine used in plugins.

**Comment by mmolab** [comment]
@CheshireCaat I will use fingerprint to create profile in other Antidect browser, and don't need to use pupeteer, playwright.
Could you tell me how to get fingerprints with API key using Javascript? Do you have any library can run on macos, or HTTP API is also ok.

**Comment by CheshireCaat** [comment]
All plugins work only under Windows, you can also use BAS to work with fingerprints - plugins get fingerprints using it in the same way, I don't have any other options for you. Since the task is not directly related to plugins, I can't help you with anything else.
