### ISSUE TITLE
[Bug]: Unable to read project file

### ISSUE THREAD

**Issue by dmitryp-rebel** [CheshireCaat/browser-with-fingerprints#35]
After update to latest starting browser:

11:07:39.901 > Launching browser: {"args":[],"headless":false}
PROJECT_PATH read : D:\projects\project.xml
11:07:39.904 > Failed browser start: Error: ENOENT: no such file or directory, open 'D:\projects\project.xml' Error: ENOENT: no such file or directory, open 'D:\projects\project.xml'
    at async open (node:internal/fs/promises:639:25)
    at async Object.readFile (node:internal/fs/promises:1242:14)
    at async #updateMeta (D:\projects\browser\.webpack\main\index.js:457014:21)
    at async RemoteEngine.runFunction (D:\projects\browser\.webpack\main\index.js:456948:22)
    at async D:\projects\browser\.webpack\main\index.js:457144:36
11:07:39.905 > Browser closed.

Problem is in engine.js. that contains wrong approach ```const PROJECT_PATH = path.resolve(__dirname, '../../../project.xml');```

In my case path variables are:

DIRNAME: D:\projects\browser\.webpack\main
PROJECT_PATH: D:\projects\project.xml

**Comment by CheshireCaat** [comment]
The __dirname inside engine should point to the plugin module root folder.

Can you please attach a test code that can be used to reproduce this problem?

**Comment by CheshireCaat** [comment]
So I see that your code is bundled, but for what purpose? Also, it seems that your bundle system problem.

Such cases was not tested, so I need detailed example.

**Comment by CheshireCaat** [comment]
Webpack overrides dirname, so try to change your webpack config.
