### ISSUE TITLE
ECONNRESET

### ISSUE THREAD

**Issue by sonyd6553** [CheshireCaat/browser-with-fingerprints#36]
hello, I experienced this error when running fingerprint usage from https://github.com/CheshireCaat/selenium-with-fingerprints, I have used the servicekey from finerprintswitcher, please help.

following is the error

Error launching browser with fingerprint: Error: aborted
    at Socket.socketCloseListener (node:_http_client:464:19)
    at Socket.emit (node:events:531:35)
    at TCP.<anonymous> (node:net:339:12) {
  code: 'ECONNRESET'
}

**Comment by bablosoft** [comment]
Please update library or use single process

**Comment by sonyd6553** [comment]
I've updated npm, and used single process using async-mutex, but the same error still appears

**Comment by bablosoft** [comment]
Wait until your IP will be unbanned

**Comment by sonyd6553** [comment]
What causes my IP to be banned? How long do I have to wait so that my IP is not banned?

**Comment by bablosoft** [comment]
Using old version with running node instance per browser

**Comment by sonyd6553** [comment]
I'm currently testing the use of fingerprintswitcher with node js and selenium, before I implement the automation, and several hours have passed, the same error still appears, please help.

**Comment by CheshireCaat** [comment]
Please update the plugin version like this:

```bash
npm i selenium-with-fingerprints@latest
```

**Comment by sonyd6553** [comment]
still not working, is there any issue with my service key?

**Comment by sonyd6553** [comment]
iam sorry, how to create ticket ?

**Comment by bablosoft** [comment]
Sorry, I messed up email and tickets. Ticket is already created.

**Comment by sonyd6553** [comment]
how long will it takes?

**Comment by CheshireCaat** [comment]
@sonyd6553 is there a `27.9.2_64.json` file in your engine folder (by default `data` folder)?

If not, try to open this URL in your browser:

http://bablosoft.com/distr/FastExecuteScript64/27.9.2/FastExecuteScript.x64.zip.meta.json

Does this page loads normally for you?

**Comment by sonyd6553** [comment]
yes it's normally open, it's comes with string..

yes, when i star running the cookies.js, the file 27.9.2_64.json coming up on data folder

**Comment by CheshireCaat** [comment]
In this case please try to download engine manually via this link:

http://downloads.bablosoft.com/distr/FastExecuteScript64/27.9.2/FastExecuteScript.x64.zip

Place it inside the `data/enige/27.9.2` and try to run your code again.

**Comment by sonyd6553** [comment]
i have to extract all the zip to the data folder and re-run the script?

**Comment by CheshireCaat** [comment]
@sonyd6553 remove the `data/script` folder and if exists, and just place zip inside the required folder - the plugic can automatically unpack it.

**Comment by sonyd6553** [comment]
well that problem is resolved now thank you.

I have a question regarding view port size and also using the Chromium browser.

How do we get the view port size that matches the fingerprint value and uses something other than chromium which is blue?

**Comment by sonyd6553** [comment]
hello, i clone and running pofile.js from this
https://github.com/CheshireCaat/playwright-with-fingerprints/tree/master/examples
but i always facing this issue,

Error: Timed out while calling the "fetch" method.
    at Timeout._onTimeout
(C:\my-path\playwright\playwright-with-fingerprints\node_modules\browser-with-fingerprints\src\plugin\connector\index.js:48:26)
    at listOnTimeout (node:internal/timers:581:17)
    at process.processTimers (node:internal/timers:519:7)

i already increase the request timeout to 180000, but still facing the same
issue. need your help.

**Comment by CheshireCaat** [comment]
There is no fetch logic in ‘profile.js’ example.

> i already increase the request timeout to 180000, but still facing the same

You decreased it, because default value is ‘300_000’. In case of free service usage it can be not enough if the query limit reached and so on.

**Comment by sonyd6553** [comment]
i already have service key, now iam running my modification script but
there's log "Unable to set correct viewport size.", how to solve this?

**Comment by CheshireCaat** [comment]
It’s just a warning, not error.

Sometimes it may happen for very large or very small viewport sizes, you can filter fingerprints that match, for example, your screen resolution and so on.

**Comment by sonyd6553** [comment]
okay, when I use the android chrome tag, why is the size of the opened
browser window not the same as the original device?

**Comment by CheshireCaat** [comment]
In some cases, it is not possible to completely adjust the dimensions, since the overall size of the window changes - in such cases, you can adjust them yourself by taking the values from the fingerprint, here is an example of how the plugin does this:

https://github.com/CheshireCaat/playwright-with-fingerprints/blob/master/src/utils.js#L65

You can use this, however, on the current version of the engine there are problems with setting very small window sizes, since restrictions were set in **Chromium** above **128** versions.

This has already been resolved and fixed in the new version of the engine, but the plugins themselves have not yet been updated. After the release of new versions, there will be fewer problems with mobile fingerprints.

I also ask you not to turn the ticket into a discussion, it is better to create a separate one for each problem, since the vast majority of the dialogue no longer relates to the original problem, thank you.
