### ISSUE TITLE
socks5 vs authentication support

### ISSUE THREAD

**Issue by nosovk** [CheshireCaat/browser-with-fingerprints#4]
In Playwright docs I found that it does not support Socks5 with authorization.
https://github.com/microsoft/playwright/issues/2425#issuecomment-775310736

But in your examples you show one: https://github.com/CheshireCaat/browser-with-fingerprints#proxy-usage

Is your plugin adds support of proxy5 with authentication?

**Comment by CheshireCaat** [comment]
Yes, all plugins use custom logic for proxy support. You should use plugin methods instead of built-in `playwright` options.

In such a case, you can use a proxy with authorization.
