### ISSUE TITLE
C# Port

### ISSUE THREAD

**Issue by Firegarden** [CheshireCaat/browser-with-fingerprints#5]
Извиняюсь, если я должен был задать этот вопрос в другом месте.

Я очень люблю эту библиотеку, но мне также очень нравится многофункциональная среда, такая как общий языковой среды выполнения (CLR) и C#.

Меня интересует, возможно ли мне портировать следующие библиотеки на C#:
[browser-with-fingerprints](https://github.com/CheshireCaat/browser-with-fingerprints)
[playwright-with-fingerprints](https://github.com/CheshireCaat/playwright-with-fingerprints)

Или это невозможно из-за необходимости портировать дополнительный код?

Буду признателен за вашу помощь и ответ на этот вопрос.

English
I apologize if this should be posted somewhere else. 

I really love this library but I also really love a proper multi threading environment such as common language runtime and C#

I wish to know is it possible for me to port these libraries
[browser-with-fingerprints](https://github.com/CheshireCaat/browser-with-fingerprints) 
[playwright-with-fingerprints](https://github.com/CheshireCaat/playwright-with-fingerprints)
to C#? 

or is this not possible because I need to port additional code 

Thank you

**Comment by Firegarden** [comment]
Причина заключается в том, что я хочу написать код, который будет запускать один новый скрейпер-браузер каждые 10 секунд, и управление таким потоком кажется нелепым в Node.js из-за его однопоточности. Я предпочитаю использовать C# вместо рабочих процессов и пула потоков Node.

English
The reason is because I wish to write code that will run one new scraper browser every 10 seconds and managing that through put is just silly with node.js because of single threaded and I prefer c# over node workers / threadpool

**Comment by bablosoft** [comment]
C# is not supported.

> The reason is because I wish to write code that will run one new scraper browser every 10 seconds and managing that through put is just silly with node.js because of single threaded and I prefer c# over node workers / threadpool

You don't need to create threads to start browsers or interact with them in parallel. All methods are async.

**Comment by Firegarden** [comment]
Thank you I really appreciate you writing back. 

> You don't need to create threads to start browsers or interact with them in parallel. All methods are async.

Async != Multithread - could you please comment on how you run a multi-threaded app using your code? Is it just node workers? It would really help if you could show a few lines of code to run multithreaded

Also if I ported the plugin code to c# do you feel it would work? or is there other reasons it can not work due to the overall system design.


Thank you

**Comment by bablosoft** [comment]
Ok, here is example

https://github.com/CheshireCaat/puppeteer-with-fingerprints/blob/master/examples/parallel.js

> Also if I ported the plugin code to c# do you feel it would work? or is there other reasons it can not work due to the overall system design.

Library can be ported to C#
